name: auth
env: blue
replicaCount: 2
image:
  repository: "<AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/auth"
  tag: "latest"
service:
  port: 80
# (Auth service might not need DB connection in this example)

product:
  env: blue   # or green
  image:
    repository: "<your-ecr-uri>"
    tag: "latest"
